server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3310/database?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
  main:
    allow-circular-references: true
  application:
    name: link-study
pagehelper:
  helper-dialect: mysql