server:
  port: 8096
#  servlet:
#    context-path: /ark

spring:
  auto:
    open-ark-url: false
  mvc:
    view:
      suffix: .jsp
      prefix: /
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/arknights?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  web:
    loginurl: http://localhost:8096/index.html
  application:
    name: arknights



logging:
  level:
    # 这个是优先的日志等级，会覆盖 logback-spring.xml 中的配置，无需在里面配置。
    root: info
    # 这个是对单个包精细控制。
    com.link.arknights.cardpool: debug
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.link.arknights.*
  global-config:
    db-config:
      id-type: AUTO
      # 数据库字段驼峰下划线转换
      db-column-underline: true
      refresh-mapper: true
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false
    # 查询结果中包含空值的列，在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 开启 sql 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 关闭 sql 日志
#    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

file:
  #文件上传目录 绝对路径 末尾不需要加 /
  path: D:/files #windows
  #path: /data/files #linux
rb:
  default:
    password: '123456'
    saas:
      # saas模式下，这些数据应该取对应租户的数据，角色这里暂时没想法，或许是在角色表加个标识，区分个人用户和公司用户的角色？
      # 基础组织关系编码
      baseOrganRelation: 'user'

# 开发工具配置：热交换关闭
devtools:
  restart:
    enabled: false

ark:
  userId:
  password:

email:
  active: qq
  qq:
    host: smtp.qq.com
    username:
    password:
  wy163:
    host: smtp.163.com
    username:
    password:

#百度翻译的配置文件
baidu-translation:
  url:
  app-id:
  api-key:
  secret-key:



