server:
  port: 8083
#  servlet:
#    context-path: /desktop

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3309/desktop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password:
  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

# 文件上传路径配置
file:
  #文件上传目录 绝对路径 末尾不需要加 /
  path: D:/files #windows
  #path: /data/files #linux

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.link.desktop.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.link.desktop: debug
    org.springframework.web: info
